language: objective-c
xcode_project: BlindAssist.xcodeproj
xcode_scheme: BlindAssist
osx_image: xcode10.2

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod --version
install:
  - pod install --repo-update
before_script:
  - ./download_model.sh
script:
  - xcodebuild -workspace BlindAssist.xcworkspace -scheme BlindAssist -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
